---
- name: Check checkmk agent registration
  shell: 'cmk-agent-ctl status | grep -q "Legacy mode: enabled"'
  register: cmk_agent_ctl_registered
  changed_when: false
  ignore_errors: true

- name: Register checkmk agent for TLS
  ansible.builtin.shell: |
    cmk-agent-ctl register \
      --server {{ checkmkagent_hostname }} \
      --site {{ checkmkagent_site }} \
      --user {{ checkmkagent_user }} \
      --hostname {{ ansible_fqdn }} \
      --password {{ checkmkagent_auth }} \
      --trust-cert
  when:
    - checkmkagent_site is defined and checkmkagent_site | length
    - checkmkagent_user is defined and checkmkagent_user | length
    - checkmkagent_auth is defined and checkmkagent_auth | length
    - checkmkagent_hostname is defined and checkmkagent_hostname | length
    - cmk_agent_ctl_registered.rc == 0
  notify: cmk-agent-ctl-daemon restart

- name: Ensure legacy checkmk agent services are stopped  + disabled
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - check_mk.socket
    - check_mk-async.service
  when: not checkmkagent_skip_systemd|default(false)
  register: checkmk_legacy_services_stopped

- name: Ensure checkmk agent services are enabled + started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - check-mk-agent-async.service
    - check-mk-agent.socket
    - cmk-agent-ctl-daemon.service
  when: not checkmkagent_skip_systemd|default(false)

- name: Restart checkmk agent controller daemon (if xinetd was restarted and/or legacy services were stopped)
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - cmk-agent-ctl-daemon.service
  when:
    - not checkmkagent_skip_systemd|default(false)
    - checkmk_legacy_services_stopped.changed|default(false) or xinetd_restarted.changed|default(false)
