---

- name: Install libregexp-common-time-perl package for check_kernel_freshness script
  apt:
    name: libregexp-common-time-perl
    state: present

- name: Ensure directory /usr/lib/check_mk_agent/local exists
  file:
    path: '/usr/lib/check_mk_agent/local'
    state: 'directory'
    owner: root
    group: root
    mode: 0755

- name: Deploy check-mk local checks
  copy:
    src: 'check-mk/local/{{ item }}'
    dest: '/usr/lib/check_mk_agent/local/{{ item }}'
    owner: root
    group: root
    mode: 0755
  with_items:
    - check_kernel_freshness
    - check_systemd
    - check_wordpress
