---

- name: Ensure directory /usr/lib/check_mk_agent/plugins exists
  file:
    path: '/usr/lib/check_mk_agent/plugins'
    state: 'directory'
    owner: root
    group: root
    mode: 0755

- name: Ensure directory /usr/lib/check_mk_agent/plugins/3600 exists
  file:
    path: '/usr/lib/check_mk_agent/plugins/3600'
    state: 'directory'
    owner: root
    group: root
    mode: 0755
  when: ansible_facts['distribution'] == "Debian"

- name: Deploy check-mk mk_apt plugin
  copy:
    src: 'check-mk/plugins/mk_apt'
    dest: '/usr/lib/check_mk_agent/plugins/3600/mk_apt'
    owner: root
    group: root
    mode: 0755
  when: ansible_facts['distribution'] == "Debian"
