---
- name: Ensure directory {{ checkmkagent_plugins_path }} exists
  file:
    path: '{{ checkmkagent_plugins_path }}'
    state: 'directory'
    owner: root
    group: root
    mode: 0755

- name: Set mk_apt plugin path
  set_fact:
    mk_apt_path: "{{ checkmkagent_plugins_path }}"

- name: Set mk_apt plugin async path
  set_fact:
    mk_apt_path: "{{ checkmkagent_plugins_path }}/{{ checkmkagent_mk_apt_delay }}"
  when:
    - checkmkagent_mk_apt_delay is defined
    - checkmkagent_mk_apt_delay > 0

- name: Ensure directory {{ mk_apt_path }} exists
  file:
    path: '{{ mk_apt_path }}'
    state: 'directory'
    owner: root
    group: root
    mode: 0755

- name: Ensure checkmk configuration directory /etc/check_mk exists
  file:
    path: '/etc/check_mk'
    state: 'directory'
    owner: root
    group: root
    mode: 0755

### checkmk agent plugin: mk_apt

- name: Download checkmk agent plugin mk_apt
  become: false
  get_url:
    url: "{{ checkmkagent_host_url }}/check_mk/agents/plugins/mk_apt"
    dest: '/tmp/'
  delegate_to: localhost
  changed_when: false
  check_mode: false

- name: Set checkmk agent plugin mk_apt DO_UPDATE configuration
  become: false
  ansible.builtin.lineinfile:
    path: '/tmp/mk_apt'
    regexp: '^DO_UPDATE='
    line: "DO_UPDATE={{ checkmkagent_mk_apt_update | default('no') }}"
  delegate_to: localhost
  changed_when: false
  check_mode: false

- name: Deploy checkmk agent plugin mk_apt
  copy:
    src: '/tmp/mk_apt'
    dest: "{{ mk_apt_path }}/mk_apt"
    owner: 'root'
    group: 'root'
    mode: 0755

### checkmk agent plugins

- name: "Deploy checkmk agent plugins"
  include_tasks: checkmk-deploy-plugins.yml
  loop: "{{ checkmkagent_plugins_enabled | select('in', checkmkagent_plugins_available) }}"
  when: checkmkagent_host_url is defined

- name: Remove checkmk agent plugin {{ item }}
  file:
    dest: '{{ checkmkagent_plugins_path }}/{{ item }}'
    state: absent
  loop: "{{ checkmkagent_plugins_available | difference(checkmkagent_plugins_enabled) }}"

### checkmk agent plugin: mk_ceph

- name: Deploy checkmk agent plugin mk_ceph configuration file
  template:
    src: 'check-mk/ceph.cfg.j2'
    dest: '/etc/check_mk/ceph.cfg'
    owner: root
    group: root
    mode: 0644
  when:
    - checkmkagent_plugins_enabled | intersect( ['mk_ceph'] )

- name: Remove checkmk agent plugin mk_ceph config file
  file:
    path: '/etc/check_mk/ceph.cfg'
    state: absent
  when:
    - not checkmkagent_plugins_enabled | intersect( ['mk_ceph'] )

### checkmk agent plugin: mk_logwatch

- name: Deploy check-mk agent plugin mk_logwatch configuration file
  template:
    src: 'check-mk/logwatch.cfg.j2'
    dest: '/etc/check_mk/logwatch.cfg'
    owner: root
    group: root
    mode: 0644
  when:
    - checkmkagent_plugins_enabled | intersect( ['mk_logwatch'] )

- name: Remove checkmk agent plugin mk_logwatch configuration file
  file:
    dest: '/etc/check_mk/logwatch.cfg'
    state: absent
  when:
    - not checkmkagent_plugins_enabled | intersect( ['mk_logwatch'] )

### checkmk agent plugin: mk_mysql

- name: Deploy check-mk agent plugin mk_mysql configuration file
  template:
    src: 'check-mk/mysql.cfg.j2'
    dest: '/etc/check_mk/mysql.cfg'
    owner: root
    group: root
    mode: 0640
  when:
    - checkmkagent_plugins_enabled | intersect( ['mk_mysql'] )

- name: Remove checkmk agent plugin mk_mysql configuration file
  file:
    dest: '/etc/check_mk/mysql.cfg'
    state: absent
  when:
    - not checkmkagent_plugins_enabled | intersect( ['mk_mysql'] )
