---
- name: Ensure /etc/xinetd.d/check_mk is absent
  file:
    path: /etc/xinetd.d/check_mk
    state: absent
  register: checkmk_xinetd
  notify: xinetd restart

- name: Flush handlers
  meta: flush_handlers

- name: Ensure check-mk-agent port 6556 is closed
  wait_for:
    port: 6556
    state: stopped
  when: checkmk_xinetd.changed
