---

- name: Install tools and utilities needed for local checks
  apt:
    name:
      - libregexp-common-time-perl  # needed for check_kernel_freshness
    state: present

- name: Ensure directory /usr/lib/check_mk_agent/local exists
  file:
    path: '/usr/lib/check_mk_agent/local'
    state: 'directory'
    owner: root
    group: root
    mode: 0755

- name: Ensure directory /usr/lib/check_mk_agent/local/3600 exists
  file:
    path: '/usr/lib/check_mk_agent/local/3600'
    state: 'directory'
    owner: root
    group: root
    mode: 0755

- name: Deploy checkmk local checks
  copy:
    src: 'check-mk/local/{{ item }}'
    dest: '/usr/lib/check_mk_agent/local/{{ item }}'
    owner: root
    group: root
    mode: 0755
  with_items:
    - check_kernel_freshness

- name: Remove obsolete checkmk local checks
  file:
    dest: '/usr/lib/check_mk_agent/local/{{ item }}'
    state: absent
  with_items:
    - check_systemd
