---
- name: Deploy checkmk local megacli checks
  copy:
    src: 'check-mk/local/{{ item }}'
    dest: '/usr/lib/check_mk_agent/local/{{ item }}'
    owner: root
    group: root
    mode: 0755
  loop:
    - check_megacli_battery
    - check_megacli_diskgroups
    - check_megacli_firmware
    - check_megacli_smart
    - check_megacli_num_disks

- name: Remove obsolete checkmk script check_num_disks
  file:
    path: '/usr/lib/check_mk_agent/local/check_num_disks'
    state: absent

- name: Deploy checkmk local check check_megacli config file
  template:
    src: 'check-mk/megacli.cfg.j2'
    dest: '/etc/check_mk/megacli.cfg'
    owner: root
    group: root
    mode: 0644
