---
# handlers file for ansible-role-checkmkagent

- name: xinetd restart
  ansible.builtin.service:
    name: xinetd
    state: restarted
  register: xinetd_restarted
  when: xinetd_check is succeeded

- name: cmk-agent-ctl-daemon restart
  ansible.builtin.service:
    name: cmk-agent-ctl-daemon
    state: restarted
