---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian10-ansible
    pre_build_image: true
    container_default_behavior: no_defaults
  - name: debian_11
    image: geerlingguy/docker-debian11-ansible
    pre_build_image: true
    container_default_behavior: no_defaults
provisioner:
  name: ansible
verifier:
  name: ansible
