---
name: Ansible Molecule

# Documentation:
#
# * https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs
# * https://github.com/marketplace/actions/ansible-molecule


# Run this workflow every time a new commit pushed to your repository
#
on:
  push:
  pull_request:
    branches: [master, main]

jobs:
  molecule:
    # Name the Job
    name: Ansible Molecule
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      # Create ansible.cfg with correct roles_path
      - run: printf '[defaults]\nroles_path=../' >ansible.cfg

      - uses: gofrolist/molecule-action@v2
